version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reandatapass
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "4232:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # postgrest:
  #   image: postgrest/postgrest
  #   environment:
  #     PGRST_DB_URI: postgres://user:password@postgres:5432/mydb
  #     PGRST_DB_SCHEMA: public
  #     PGRST_DB_ANON_ROLE: web_anon
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres

  # swaggerui:
  #   image: swaggerapi/swagger-ui
  #   environment:
  #     SWAGGER_JSON: /swagger.json
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./swagger/swagger.json:/swagger.json
  #   depends_on:
  #     - postgrest

volumes:
  postgres_data:
